/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

interface AwsConfig {
  aws_project_region: string;
  aws_cognito_identity_pool_id: string;
  aws_cognito_region: string;
  aws_user_pools_id: string;
  aws_user_pools_web_client_id: string;
  oauth: Record<string, unknown>;
  aws_cognito_username_attributes: string[];
  aws_cognito_social_providers: string[];
  aws_cognito_signup_attributes: string[];
  aws_cognito_mfa_configuration: string;
  aws_cognito_mfa_types: string[];
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: number;
    passwordPolicyCharacters: string[];
  };
  aws_cognito_verification_mechanisms: string[];
}

const awsconfig: AwsConfig = {
  aws_project_region: import.meta.env.VITE_AWS_REGION,
  aws_cognito_identity_pool_id: import.meta.env
    .VITE_AWS_COGNITO_IDENTITY_POOL_ID,
  aws_cognito_region: import.meta.env.VITE_AWS_REGION,
  aws_user_pools_id: import.meta.env.VITE_AWS_COGNITO_USER_POOLS_ID,
  aws_user_pools_web_client_id: import.meta.env
    .VITE_AWS_COGNITO_USER_POOLS_WEB_CLIENT_ID,
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [
    import.meta.env.VITE_AWS_COGNITO_SIGNUP_ATTRIBUTES,
  ],
  aws_cognito_mfa_configuration: import.meta.env
    .VITE_AWS_COGNITO_MFA_CONFIGURATION,
  aws_cognito_mfa_types: [import.meta.env.VITE_AWS_COGNITO_MFA_TYPES],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: Number(
      import.meta.env.VITE_AWS_COGNITO_PASSWORD_MIN_LENGTH
    ),
    passwordPolicyCharacters: import.meta.env
      .VITE_AWS_COGNITO_PASSWORD_POLICY_CHARACTERS
      ? import.meta.env.VITE_AWS_COGNITO_PASSWORD_POLICY_CHARACTERS.split(",")
      : [],
  },
  aws_cognito_verification_mechanisms: [
    import.meta.env.VITE_AWS_COGNITO_VERIFICATION_MECHANISMS,
  ],
};

export default awsconfig;
